def generateTalentList():
    talents = {
        "Fliegen":{"check":"MU/IN/GE","fw":0,"category":"Körpertalente"},
        "Gaukeleien":{"check":"MU/CH/FF","fw":0,"category":"Körpertalente"},
        "Klettern":{"check":"MU/GE/KK","fw":0,"category":"Körpertalente"},
        "Körperbeherrschung":{"check":"GE/GE/KO","fw":0,"category":"Körpertalente"},
        "Kraftakt":{"check":"KO/KK/KK","fw":0,"category":"Körpertalente"},
        "Reiten":{"check":"CH/GE/KK","fw":0,"category":"Körpertalente"},
        "Schwimmen":{"check":"GE/KO/KK","fw":0,"category":"Körpertalente"},
        "Selbstbeherrschung":{"check":"MU/MU/KO","fw":0,"category":"Körpertalente"},
        "Singen":{"check":"KL/CH/KO","fw":0,"category":"Körpertalente"},
        "Sinnesschärfe":{"check":"KL/IN/IN","fw":0,"category":"Körpertalente"},
        "Tanzen":{"check":"KL/CH/GE","fw":0,"category":"Körpertalente"},
        "Taschendiebstahl":{"check":"MU/FF/GE","fw":0,"category":"Körpertalente"},
        "Verbergen":{"check":"MU/IN/GE","fw":0,"category":"Körpertalente"},
        "Zechen":{"check":"KL/KO/KK","fw":0,"category":"Körpertalente"},

        "Bekehren und Überzeugen":{"check":"MU/KL/CH","fw":0,"category":"Gesellschaftstalente"},
        "Betören":{"check":"MU/CH/CH","fw":0,"category":"Gesellschaftstalente"},
        "Einschüchtern":{"check":"MU/IN/CH","fw":0,"category":"Gesellschaftstalente"},
        "Etikette":{"check":"KL/IN/CH","fw":0,"category":"Gesellschaftstalente"},
        "Gassenwissen":{"check":"KL/IN/CH","fw":0,"category":"Gesellschaftstalente"},
        "Menschenkenntnis":{"check":"KL/IN/CH","fw":0,"category":"Gesellschaftstalente"},
        "Überreden":{"check":"MU/IN/CH","fw":0,"category":"Gesellschaftstalente"},
        "Verkleiden":{"check":"IN/CH/GE","fw":0,"category":"Gesellschaftstalente"},
        "Willenskraft":{"check":"MU/IN/CH","fw":0,"category":"Gesellschaftstalente"},

        "Fährtensuchen":{"check":"MU/IN/GE","fw":0,"category":"Naturtalente"},
        "Fesseln":{"check":"KL/FF/KK","fw":0,"category":"Naturtalente"},
        "Fischen und Angeln":{"check":"FF/GE/KO","fw":0,"category":"Naturtalente"},
        "Orientierung":{"check":"KL/IN/IN","fw":0,"category":"Naturtalente"},
        "Pflanzenkunde":{"check":"KL/FF/KO","fw":0,"category":"Naturtalente"},
        "Tierkunde":{"check":"MU/MU/CH","fw":0,"category":"Naturtalente"},
        "Wildnisleben":{"check":"MU/GE/KO","fw":0,"category":"Naturtalente"},

        "Brett und Glücksspiel ":{"check":"KL/KL/IN","fw":0,"category":"Wissenstalente"},
        "Geographie":{"check":"KL/KL/IN","fw":0,"category":"Wissenstalente"},
        "Geschichtswissen":{"check":"KL/KL/IN","fw":0,"category":"Wissenstalente"},
        "Götter und Kulte":{"check":"KL/KL/IN","fw":0,"category":"Wissenstalente"},
        "Kriegskunst":{"check":"MU/KL/IN","fw":0,"category":"Wissenstalente"},
        "Magiekunde":{"check":"KL/KL/IN","fw":0,"category":"Wissenstalente"},
        "Mechanik":{"check":"KL/KL/FF","fw":0,"category":"Wissenstalente"},
        "Rechnen":{"check":"KL/KL/IN","fw":0,"category":"Wissenstalente"},
        "Rechtskunde":{"check":"KL/KL/IN","fw":0,"category":"Wissenstalente"},
        "Sagen und Legenden":{"check":"KL/KL/IN","fw":0,"category":"Wissenstalente"},
        "Sphärenkunde":{"check":"KL/KL/IN","fw":0,"category":"Wissenstalente"},
        "Sternkunde":{"check":"KL/KL/IN","fw":0,"category":"Wissenstalente"},

        "Alchimie":{"check":"MU/KL/FF","fw":0,"category":"Handwerkstalente"},
        "Boote und Schiffe":{"check":"FF/GE/KK","fw":0,"category":"Handwerkstalente"},
        "Fahrzeuge":{"check":"CH/FF/KO","fw":0,"category":"Handwerkstalente"},
        "Handel":{"check":"KL/IN/CH","fw":0,"category":"Handwerkstalente"},
        "Heilkunde Gift":{"check":"MU/KL/IN","fw":0,"category":"Handwerkstalente"},
        "Heilkunde Krankheiten":{"check":"MU/IN/KO","fw":0,"category":"Handwerkstalente"},
        "Heilkunde Seele":{"check":"IN/CH/KO","fw":0,"category":"Handwerkstalente"},
        "Heilkunde Wunden":{"check":"KL/FF/FF","fw":0,"category":"Handwerkstalente"},
        "Holzbearbeitung":{"check":"FF/GE/KK","fw":0,"category":"Handwerkstalente"},
        "Lebensmittelbearbeitung":{"check":"IN/FF/FF","fw":0,"category":"Handwerkstalente"},
        "Lederbearbeitung":{"check":"FF/GE/KO","fw":0,"category":"Handwerkstalente"},
        "Malen und Zeichnen":{"check":"IN/FF/FF","fw":0,"category":"Handwerkstalente"},
        "Metallbearbeitung":{"check":"FF/KO/KK","fw":0,"category":"Handwerkstalente"},
        "Musizieren":{"check":"CH/FF/KO","fw":0,"category":"Handwerkstalente"},
        "Schlösserknacken":{"check":"IN/FF/FF","fw":0,"category":"Handwerkstalente"},
        "Steinbearbeitung":{"check":"FF/FF/KK","fw":0,"category":"Handwerkstalente"},
        "Stoffbearbeitung":{"check":"KL/FF/FF","fw":0,"category":"Handwerkstalente"},
    }
    output = []
    for k,v in talents.items():
        splitAtts = v["check"].split("/")
        output.append({
            "name":k,
            "category":v["category"],
            "fw":0,
            "att_1":splitAtts[0],
            "att_2":splitAtts[1],
            "att_3":splitAtts[2],
        })
    return output