name: Deploy

on: workflow_dispatch

env:
  #VERSION: ${{ github.ref_name }}
  CODE_PATH: /home/soulforger/actions-runner-2/_work/soulforger.net_api/soulforger.net_api

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - run: |
          if [[ "${{ github.ref_name }}" == *stable* ]]; then
            echo "LINE=stable-" >> $GITHUB_ENV
          else
            echo "LINE=beta-" >> $GITHUB_ENV
          fi
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: ${{ env.CODE_PATH }}
      - name: Stop Old Container
        run: docker stop soulforger-${LINE}api || true
      - name: Remove Old Container
        run: docker rm soulforger-${LINE}api || true
      - name: Remove Old Image
        run: docker rmi soulforger-${LINE}api || true
  build:
    runs-on: self-hosted
    needs: prepare
    steps:
      - run: |
          if [[ "${{ github.ref_name }}" == *stable* ]]; then
            echo "LINE=stable-" >> $GITHUB_ENV
          else
            echo "LINE=beta-" >> $GITHUB_ENV
          fi
      - name: Build Docker Image
        run: docker build -t soulforger-${LINE}api ${{ env.CODE_PATH }}
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - run: |
          if [[ "${{ github.ref_name }}" == *stable* ]]; then
            echo "LINE=stable-" >> $GITHUB_ENV
            echo "SERVICE_PORT=8081" >> $GITHUB_ENV
          else
            echo "LINE=beta-" >> $GITHUB_ENV
            echo "SERVICE_PORT=8083" >> $GITHUB_ENV
          fi
      - name: Run Docker Container
        run: docker run -d --env-file /home/soulforger/${LINE}backend.env --name soulforger-${LINE}api -p ${SERVICE_PORT}:8080 soulforger-${LINE}api